package addressbook.tests;// Generated by Selenium IDE

import addressbook.model.GroupData;
import org.testng.annotations.Test;

public class GroupCreationTests extends TestBase {

    @Test
    public void testGroupCreation() {
        app.getNavigationHelper().gotoGroupPage();
        app.getGroupHelper().groupCreate(new GroupData("test1", null, null));
    }

}
